export const GET_PROJECTS = "GET_PROJECTS";
export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_SLOT = "ADD_SLOT";
export const SLOTS_LOADING = "SLOTS_LOADING";
